import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <head>
        <title>OCR de Nota Manuscrita y Transformación</title>
      </head>
      <body style={{ backgroundColor: "#fff", color: "#000" }}>
        {children}
      </body>
    </html>
  );
}
